name: Deploy

on:
  push:
    branches:
      - main   # 👈 cámbialo a tu rama principal si no es main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 👇 Aquí va el bloque que se cambió
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 👇 Este es un ejemplo de despliegue en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # cambia a ./build si usas React o Vite
